// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/bundle.schema.json.
// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`.

/**
 * One kit component. 'type' discriminates the shape.
 */
export type Component = DeviceComponent | BundleComponent | CableComponent | AccessoryComponent;
/**
 * A component device. Provide it inline (device + ports [+ power/physical/...]) OR reference an external device document.
 */
export type DeviceComponent = {
  type: "device";
  quantity?: number;
  /**
   * Role/label within the kit, e.g. 'Touch Screen', 'Presentation Transmitter'.
   */
  designator?: string;
  /**
   * Optional component-local id.
   */
  id?: string;
  device?: Device;
  ports?: Port[];
  power?: Power;
  physical?: Physical;
  standards?: Standard[];
  parameters?: Parameters;
  ref?: Ref;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & DeviceComponent1;
/**
 * One externally accessible connector (or a group of identical connectors), the physical link it provides, and the logical signal flows it carries.
 */
export type Port = {
  [k: string]: unknown;
} & {
  /**
   * Identifier unique within this device.
   */
  id: string;
  /**
   * Human-facing label as silkscreened on the device, e.g. 'HDMI INPUT 1'.
   */
  label?: string;
  /**
   * Optional terse label for tight layouts (e.g. an I/O-table cell), used only when 'label' is too long; presentation hint, no semantic effect.
   */
  shortLabel?: string;
  /**
   * Overall port direction. Individual signal flows may override via signal.direction.
   */
  direction: "input" | "output" | "bidirectional";
  /**
   * Controlled connector (physical jack) vocabulary. Use 'other' with connectorOther when not listed. The connector describes the jack only; the transmission standard belongs in port.link and the carried flows in port.signals.
   */
  connector:
    | "hdmi-type-a"
    | "hdmi-type-b"
    | "hdmi-type-c"
    | "hdmi-type-d"
    | "displayport"
    | "mini-displayport"
    | "dvi-d"
    | "dvi-i"
    | "dvi-a"
    | "hd15-vga"
    | "usb-a"
    | "usb-b"
    | "usb-b-mini"
    | "usb-b-micro"
    | "usb-c"
    | "rj45"
    | "rj45-shielded"
    | "ethercon"
    | "sfp"
    | "sfp+"
    | "sfp28"
    | "qsfp"
    | "qsfp+"
    | "qsfp28"
    | "fiber-lc"
    | "fiber-lc-duplex"
    | "fiber-sc"
    | "fiber-st"
    | "fiber-mpo"
    | "fiber-mtp"
    | "opticalcon"
    | "bnc"
    | "bnc-din-1.0-2.3"
    | "rca"
    | "f-type"
    | "toslink"
    | "mini-toslink"
    | "xlr-3-m"
    | "xlr-3-f"
    | "xlr-5-m"
    | "xlr-5-f"
    | "mini-xlr-3"
    | "mini-xlr-4"
    | "xlr-combo"
    | "euroblock-3.5mm"
    | "euroblock-5.08mm"
    | "phoenix"
    | "terminal-block"
    | "captive-screw"
    | "trs-3.5mm"
    | "trrs-3.5mm"
    | "ts-6.35mm"
    | "trs-6.35mm"
    | "speakon-nl2"
    | "speakon-nl4"
    | "speakon-nl8"
    | "binding-post"
    | "banana"
    | "db9"
    | "db15"
    | "db25"
    | "rj11"
    | "rj12"
    | "sma"
    | "rp-sma"
    | "tnc"
    | "n-type"
    | "iec-c8"
    | "iec-c14"
    | "iec-c16"
    | "iec-c20"
    | "powercon"
    | "powercon-true1"
    | "nema-5-15"
    | "barrel-dc"
    | "phoenix-power"
    | "other";
  /**
   * Free-text connector name; required when connector is 'other'.
   */
  connectorOther?: string;
  /**
   * Number of identical, separately addressable connectors collapsed into this entry. Use individual entries when labels or positions differ.
   */
  count?: number;
  /**
   * Physical poles/pins on a terminal-block-style connector (e.g. a 3-pole Phoenix). Independent of how many signal channels are carried; see signal.channels.
   */
  poleCount?: number;
  /**
   * Optional pole-to-function map for pin-level detail (e.g. Phoenix RS-232 pinout).
   */
  poles?: {
    pole: number;
    /**
     * e.g. 'tx', 'rx', 'gnd', 'audio-l+', 'gpio-1'.
     */
    function?: string;
    label?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  }[];
  link?: Link;
  /**
   * One or more concurrent logical signal flows carried by this connector. A single network or USB connector commonly carries several (e.g. Dante + AES67 + AV-over-IP + control + general LAN).
   *
   * @minItems 1
   */
  signals: [Signal, ...Signal[]];
  /**
   * Optional physical layout hint for rendering the device face.
   */
  location?: {
    face?: "front" | "rear" | "top" | "bottom" | "left" | "right";
    /**
     * Logical grouping label, e.g. 'inputs', 'outputs', 'control'.
     */
    group?: string;
    order?: number;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * The physical transmission layer ('pipe') a port provides, independent of the logical flows it carries. PoE, link speed, USB power delivery, and fiber characteristics live here once per port rather than being duplicated across flows.
 */
export type Link = {
  [k: string]: unknown;
} & {
  type?:
    | "ethernet"
    | "usb"
    | "thunderbolt"
    | "sdi"
    | "hdmi"
    | "displayport"
    | "dvi"
    | "vga"
    | "analog-audio"
    | "aes3"
    | "fiber"
    | "coax"
    | "twisted-pair"
    | "wireless"
    | "mains"
    | "dc"
    | "other";
  typeOther?: string;
  /**
   * Transmission standard/version, e.g. 'hdmi-2.1', 'dp-1.4', '12g-sdi', 'hdbaset-3', 'usb-3.2-gen2', '1000base-t'.
   */
  standard?: string;
  /**
   * Link speed where applicable, e.g. '100m', '1g', '2.5g', '5g', '10g', '25g', '40g', '100g'.
   */
  speed?: string;
  /**
   * Raw link bandwidth in Gbps, when useful.
   */
  bandwidthGbps?: number;
  /**
   * Power over Ethernet capability of this link.
   */
  poe?: {
    standard?: "802.3af" | "802.3at" | "802.3bt-type3" | "802.3bt-type4" | "passive" | "other";
    /**
     * pse = sources power; pd = consumes power.
     */
    role?: "pse" | "pd";
    classWatts?: number;
    notes?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * USB Power Delivery budget on this link, in watts.
   */
  powerDeliveryWatts?: number;
  /**
   * Physical USB role of the connector.
   */
  usbRole?: "host" | "device" | "dual-role";
  fiberMode?: "single-mode" | "multi-mode";
  fiberStrands?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * A logical signal flow carried by a port. The 'domain' discriminates the attribute set; 'transport' names the protocol/standard carrying it.
 */
export type Signal = SignalVideo | SignalAudio | SignalControl | SignalNetwork | SignalData | SignalPower;
export type SignalVideo = {
  [k: string]: unknown;
} & {
  domain: "video";
  transport?:
    | "hdmi"
    | "displayport"
    | "dvi"
    | "vga"
    | "component"
    | "composite"
    | "s-video"
    | "sdi-3g"
    | "sdi-6g"
    | "sdi-12g"
    | "hdbaset"
    | "sdvoe"
    | "ndi"
    | "ndi-hx"
    | "ipmx"
    | "dante-av"
    | "av-over-ip"
    | "usb-uvc"
    | "h.264"
    | "h.265"
    | "mjpeg"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * e.g. '4096x2160' or '3840x2160'.
   */
  maxResolution?: string;
  maxRefreshHz?: number;
  colorDepthBits?: number;
  chromaSubsampling?: "4:4:4" | "4:2:2" | "4:2:0";
  /**
   * HDCP version, e.g. '1.4', '2.2', '2.3', or 'none'.
   */
  hdcp?: string;
  /**
   * Supported HDR formats, e.g. 'hdr10', 'hdr10+', 'dolby-vision', 'hlg'.
   */
  hdr?: string[];
  /**
   * Port performs scaling/format conversion.
   */
  scaling?: boolean;
  edidManagement?: boolean;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type SignalAudio = {
  [k: string]: unknown;
} & {
  domain: "audio";
  transport?:
    | "analog"
    | "lpcm"
    | "aes3"
    | "spdif"
    | "adat"
    | "madi"
    | "arc"
    | "earc"
    | "dante"
    | "aes67"
    | "avb"
    | "milan"
    | "cobranet"
    | "livewire"
    | "usb-uac"
    | "bluetooth"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * Audio channels within one circuit (e.g. 2 for a stereo pair).
   */
  maxChannelsPerCircuit?: number;
  /**
   * For audio-over-IP, the number of network audio channels (e.g. Dante 64x64 -> 64).
   */
  networkChannels?: number;
  /**
   * Nominal level in dBu (e.g. +4 line, -10 consumer ~ -7.78 dBu).
   */
  levelDbu?: number;
  impedanceOhms?: number;
  sampleRateHz?: number;
  bitDepth?: number;
  /**
   * 48V phantom power available (typically mic inputs).
   */
  phantomPower?: boolean;
  balanced?: boolean;
  /**
   * Adjustable gain range, e.g. '0-60'.
   */
  gainDbRange?: string;
  /**
   * Max SPL for a transducer, in dB.
   */
  maxSplDb?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type SignalControl = {
  [k: string]: unknown;
} & {
  domain: "control";
  transport?:
    | "rs-232"
    | "rs-422"
    | "rs-485"
    | "ir"
    | "cec"
    | "gpio"
    | "contact-closure"
    | "relay"
    | "usb-hid"
    | "usb-cdc"
    | "cresnet"
    | "knx"
    | "dali"
    | "dmx512"
    | "artnet"
    | "sacn"
    | "onvif"
    | "sip"
    | "bacnet"
    | "modbus"
    | "mqtt"
    | "http"
    | "rest"
    | "telnet"
    | "ssh"
    | "ip-control"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * e.g. '9600-115200'.
   */
  baudRange?: string;
  /**
   * IR carrier frequency, e.g. 38.
   */
  irCarrierKhz?: number;
  /**
   * e.g. 'controller', 'controlled'.
   */
  roles?: string[];
  /**
   * Bus protocol where multiple devices share the line (RS-485, DMX, KNX, DALI).
   */
  busAddressable?: boolean;
  maxBusDevices?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * General IP connectivity / infrastructure flow (LAN, control network, management). Service-specific media flows that happen to ride Ethernet (Dante, AES67, SDVoE, NDI...) are modeled under their own domain (audio/video) with the matching transport.
 */
export type SignalNetwork = {
  [k: string]: unknown;
} & {
  domain: "network";
  transport?: "ethernet" | "ip" | "control-network" | "av-network" | "management" | "vlan-trunk" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  vlanCapable?: boolean;
  managed?: boolean;
  redundancy?: "none" | "lag" | "smpte-2022-7" | "parallel" | "stp" | "other";
  /**
   * Additional transported AV/IT protocols not broken out as separate flows, e.g. 'dante', 'ndi', 'sdvoe'.
   */
  protocols?: string[];
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * Non-AV data payload (e.g. USB data, mass storage, generic file transfer).
 */
export type SignalData = {
  [k: string]: unknown;
} & {
  domain: "data";
  transport?: "usb-data" | "usb-mass-storage" | "thunderbolt" | "file-transfer" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  rateGbps?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * Power delivery as a port's function (e.g. a DC output, 12V trigger, PDU outlet, speaker drive). Note: PoE belongs on link.poe and USB-PD on link.powerDeliveryWatts.
 */
export type SignalPower = {
  [k: string]: unknown;
} & {
  domain: "power";
  transport?: "ac" | "dc" | "usb-pd" | "phantom" | "trigger" | "wireless-power" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * source = supplies power out of this port; sink = draws power in.
   */
  role?: "source" | "sink";
  /**
   * Volts.
   */
  nominalVoltage?: number;
  maxWatts?: number;
  maxAmps?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * A reference to an external device/bundle/cable document by id and/or URL.
 */
export type Ref = Ref1 & {
  /**
   * Document id, e.g. 'crestron/tsw-1070-b-s-t-v'.
   */
  id?: string;
  url?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & Ref1 & {
    /**
     * Document id, e.g. 'crestron/tsw-1070-b-s-t-v'.
     */
    id?: string;
    url?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  } & Ref1 & {
    /**
     * Document id, e.g. 'crestron/tsw-1070-b-s-t-v'.
     */
    id?: string;
    url?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
export type Ref1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
export type DeviceComponent1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * A nested sub-assembly (a bundle within a bundle). Provide it inline (bundle + components) OR reference an external bundle.
 */
export type BundleComponent = {
  type: "bundle";
  quantity?: number;
  designator?: string;
  id?: string;
  bundle?: BundleIdentity;
  /**
   * @minItems 1
   */
  components?: [Component, ...Component[]];
  ref?: Ref;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & BundleComponent1;
export type BundleComponent1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };
/**
 * A cable in the kit. Provide it inline OR reference an external cable document.
 */
export type CableComponent = {
  type: "cable";
  quantity?: number;
  /**
   * Role, e.g. 'Primary display', 'UC Engine LAN'.
   */
  designator?: string;
  id?: string;
  cable?: Cable;
  ref?: Ref;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & CableComponent1;
export type CableEnd = {
  [k: string]: unknown;
} & {
  id?: string;
  /**
   * e.g. 'Display end', 'To RX', 'A', 'B'.
   */
  label?: string;
  /**
   * Controlled connector (physical jack) vocabulary. Use 'other' with connectorOther when not listed. The connector describes the jack only; the transmission standard belongs in port.link and the carried flows in port.signals.
   */
  connector:
    | "hdmi-type-a"
    | "hdmi-type-b"
    | "hdmi-type-c"
    | "hdmi-type-d"
    | "displayport"
    | "mini-displayport"
    | "dvi-d"
    | "dvi-i"
    | "dvi-a"
    | "hd15-vga"
    | "usb-a"
    | "usb-b"
    | "usb-b-mini"
    | "usb-b-micro"
    | "usb-c"
    | "rj45"
    | "rj45-shielded"
    | "ethercon"
    | "sfp"
    | "sfp+"
    | "sfp28"
    | "qsfp"
    | "qsfp+"
    | "qsfp28"
    | "fiber-lc"
    | "fiber-lc-duplex"
    | "fiber-sc"
    | "fiber-st"
    | "fiber-mpo"
    | "fiber-mtp"
    | "opticalcon"
    | "bnc"
    | "bnc-din-1.0-2.3"
    | "rca"
    | "f-type"
    | "toslink"
    | "mini-toslink"
    | "xlr-3-m"
    | "xlr-3-f"
    | "xlr-5-m"
    | "xlr-5-f"
    | "mini-xlr-3"
    | "mini-xlr-4"
    | "xlr-combo"
    | "euroblock-3.5mm"
    | "euroblock-5.08mm"
    | "phoenix"
    | "terminal-block"
    | "captive-screw"
    | "trs-3.5mm"
    | "trrs-3.5mm"
    | "ts-6.35mm"
    | "trs-6.35mm"
    | "speakon-nl2"
    | "speakon-nl4"
    | "speakon-nl8"
    | "binding-post"
    | "banana"
    | "db9"
    | "db15"
    | "db25"
    | "rj11"
    | "rj12"
    | "sma"
    | "rp-sma"
    | "tnc"
    | "n-type"
    | "iec-c8"
    | "iec-c14"
    | "iec-c16"
    | "iec-c20"
    | "powercon"
    | "powercon-true1"
    | "nema-5-15"
    | "barrel-dc"
    | "phoenix-power"
    | "other";
  connectorOther?: string;
  gender?: "male" | "female";
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & {
  id?: string;
  /**
   * e.g. 'Display end', 'To RX', 'A', 'B'.
   */
  label?: string;
  /**
   * Controlled connector (physical jack) vocabulary. Use 'other' with connectorOther when not listed. The connector describes the jack only; the transmission standard belongs in port.link and the carried flows in port.signals.
   */
  connector:
    | "hdmi-type-a"
    | "hdmi-type-b"
    | "hdmi-type-c"
    | "hdmi-type-d"
    | "displayport"
    | "mini-displayport"
    | "dvi-d"
    | "dvi-i"
    | "dvi-a"
    | "hd15-vga"
    | "usb-a"
    | "usb-b"
    | "usb-b-mini"
    | "usb-b-micro"
    | "usb-c"
    | "rj45"
    | "rj45-shielded"
    | "ethercon"
    | "sfp"
    | "sfp+"
    | "sfp28"
    | "qsfp"
    | "qsfp+"
    | "qsfp28"
    | "fiber-lc"
    | "fiber-lc-duplex"
    | "fiber-sc"
    | "fiber-st"
    | "fiber-mpo"
    | "fiber-mtp"
    | "opticalcon"
    | "bnc"
    | "bnc-din-1.0-2.3"
    | "rca"
    | "f-type"
    | "toslink"
    | "mini-toslink"
    | "xlr-3-m"
    | "xlr-3-f"
    | "xlr-5-m"
    | "xlr-5-f"
    | "mini-xlr-3"
    | "mini-xlr-4"
    | "xlr-combo"
    | "euroblock-3.5mm"
    | "euroblock-5.08mm"
    | "phoenix"
    | "terminal-block"
    | "captive-screw"
    | "trs-3.5mm"
    | "trrs-3.5mm"
    | "ts-6.35mm"
    | "trs-6.35mm"
    | "speakon-nl2"
    | "speakon-nl4"
    | "speakon-nl8"
    | "binding-post"
    | "banana"
    | "db9"
    | "db15"
    | "db25"
    | "rj11"
    | "rj12"
    | "sma"
    | "rp-sma"
    | "tnc"
    | "n-type"
    | "iec-c8"
    | "iec-c14"
    | "iec-c16"
    | "iec-c20"
    | "powercon"
    | "powercon-true1"
    | "nema-5-15"
    | "barrel-dc"
    | "phoenix-power"
    | "other";
  connectorOther?: string;
  gender?: "male" | "female";
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type CableComponent1 =
  | {
      [k: string]: unknown;
    }
  | {
      [k: string]: unknown;
    };

/**
 * A kit or assembly: one orderable part number that contains multiple component devices, nested sub-assemblies, factory-terminated cables, and non-I/O accessories. Component devices remain full ODIO devices (rendered as separate blocks); they may be embedded inline or referenced.
 */
export interface OpenDeviceIOBundle {
  $schema?: string;
  odioVersion: string;
  /**
   * Document discriminator. Device documents have no 'kind'; bundles and cables do.
   */
  kind: "bundle";
  id: string;
  bundle: BundleIdentity;
  /**
   * The kit contents. Each component is a device, a nested bundle, a cable, or an accessory.
   *
   * @minItems 1
   */
  components: [Component, ...Component[]];
  standards?: Standard[];
  parameters?: Parameters;
  provenance?: Provenance;
  /**
   * This interface was referenced by `OpenDeviceIOBundle`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Kit/assembly identity. 'model' is the orderable part number.
 */
export interface BundleIdentity {
  manufacturer: string;
  /**
   * Kit/assembly part number.
   */
  model: string;
  revision?: string;
  category?: string;
  productLine?: string;
  sku?: string;
  gtin?: string;
  productUrl?: string;
  datasheetUrl?: string;
  description?: string;
  /**
   * This interface was referenced by `BundleIdentity`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Device identity and classification.
 */
export interface Device {
  manufacturer: string;
  model: string;
  /**
   * Hardware revision, if applicable.
   */
  revision?: string;
  /**
   * Dotted taxonomy path, e.g. 'av/extender/transmitter' or 'it/network/switch'.
   */
  category?: string;
  productLine?: string;
  /**
   * GTIN/UPC/EAN.
   */
  gtin?: string;
  /**
   * Manufacturer SKU / part number.
   */
  sku?: string;
  productUrl?: string;
  datasheetUrl?: string;
  releaseDate?: string;
  /**
   * This interface was referenced by `Device`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Device-level power characteristics.
 */
export interface Power {
  inputs?: {
    type: "ac" | "dc" | "poe" | "usb-pd";
    /**
     * e.g. '100-240V'.
     */
    voltageRange?: string;
    /**
     * Volts (typically for DC).
     */
    nominalVoltage?: number;
    /**
     * e.g. '50/60'.
     */
    frequencyHz?: string;
    /**
     * Connector vocabulary value, e.g. 'iec-c14', 'barrel-dc'.
     */
    connector?: string;
    /**
     * For PoE inputs, e.g. '802.3at'.
     */
    standard?: string;
    notes?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  }[];
  consumptionWatts?: {
    typical?: number;
    max?: number;
    standby?: number;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * Optional; derivable from watts (W x 3.412) if absent.
   */
  heatBtuPerHour?: number;
  /**
   * True if the device has redundant power supplies.
   */
  redundant?: boolean;
  notes?: string;
  /**
   * This interface was referenced by `Power`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Physical dimensions and mounting. SI units; dimensions in millimetres, mass in grams.
 */
export interface Physical {
  dimensionsMm?: {
    width?: number;
    height?: number;
    depth?: number;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  weightGrams?: number;
  /**
   * Height in rack units (U). 0 if not rack-mounted; 0.5 for half-U, etc.
   */
  rackUnits?: number;
  rackMountable?: boolean;
  rackWidth?: "full" | "half" | "third" | "quarter";
  mounting?: ("rack" | "surface" | "wall" | "under-table" | "pole" | "ceiling" | "din-rail" | "vesa" | "desktop")[];
  /**
   * e.g. 'IP20', 'IP65'.
   */
  ipRating?: string;
  color?: string;
  notes?: string;
  /**
   * This interface was referenced by `Physical`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * A device-level compliance or interoperability standard (safety, EMC, environmental). Per-signal interop standards (Dante, AES67, etc.) are expressed as signal.transport.
 */
export interface Standard {
  category?: "safety" | "emc" | "env" | "av" | "network" | "wireless" | "other";
  /**
   * e.g. 'UL 62368-1', 'FCC Part 15 Class A', 'HDBaseT', 'AES67', 'RoHS'.
   */
  name: string;
  detail?: string;
  /**
   * This interface was referenced by `Standard`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Free-form parametric data with no typed home (operating temperature, latency, MTBF, warranty, etc.). Values may be primitives or { value, unit } objects.
 */
export interface Parameters {
  [k: string]:
    | string
    | number
    | boolean
    | {
        value: string | number | boolean;
        unit?: string;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-".
         */
        [k: string]: unknown;
      };
}
/**
 * The cable body. May be embedded in a bundle component or wrapped as a standalone cable document.
 */
export interface Cable {
  manufacturer?: string;
  /**
   * Cable part number / model.
   */
  model?: string;
  sku?: string;
  label?: string;
  /**
   * True if terminated at the factory (vs field-terminated).
   */
  factoryTerminated?: boolean;
  lengthMeters?: number;
  /**
   * Length as printed, e.g. '6 ft (1.8 m)'.
   */
  lengthLabel?: string;
  shielded?: boolean;
  plenum?: boolean;
  /**
   * Signal(s) the cable conveys end to end (reuses the device signal model).
   */
  carries?: Signal[];
  /**
   * The cable's terminations. Usually 2; more for breakout/snake cables.
   *
   * @minItems 1
   */
  ends: [CableEnd, ...CableEnd[]];
  notes?: string;
  /**
   * This interface was referenced by `Cable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * A non-I/O accessory (mounting hardware, brackets, etc.) — a BOM line item with no ports.
 */
export interface AccessoryComponent {
  type: "accessory";
  quantity?: number;
  designator?: string;
  name: string;
  /**
   * Part number, if any.
   */
  model?: string;
  manufacturer?: string;
  description?: string;
  /**
   * This interface was referenced by `AccessoryComponent`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Where this data came from and how trustworthy it is.
 */
export interface Provenance {
  /**
   * Tool that produced the file, e.g. 'genie/0.1.0', or 'manual'.
   */
  generator?: string;
  method?: "llm-extraction" | "manual" | "manufacturer";
  sourceDocuments?: {
    title?: string;
    url?: string;
    sha256?: string;
    retrieved?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  }[];
  validation?: {
    status?: "draft" | "reviewed" | "manufacturer-verified";
    by?: string;
    date?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  confidence?: {
    overall?: number;
    /**
     * JSON paths the generator was unsure about, for human review.
     */
    lowConfidenceFields?: string[];
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * This interface was referenced by `Provenance`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
