// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/cable.schema.json.
// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`.

/**
 * A logical signal flow carried by a port. The 'domain' discriminates the attribute set; 'transport' names the protocol/standard carrying it.
 */
export type Signal = SignalVideo | SignalAudio | SignalControl | SignalNetwork | SignalData | SignalPower;
export type SignalVideo = {
  [k: string]: unknown;
} & {
  domain: "video";
  transport?:
    | "hdmi"
    | "displayport"
    | "dvi"
    | "vga"
    | "component"
    | "composite"
    | "s-video"
    | "sdi-3g"
    | "sdi-6g"
    | "sdi-12g"
    | "hdbaset"
    | "sdvoe"
    | "ndi"
    | "ndi-hx"
    | "ipmx"
    | "dante-av"
    | "av-over-ip"
    | "usb-uvc"
    | "h.264"
    | "h.265"
    | "mjpeg"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * e.g. '4096x2160' or '3840x2160'.
   */
  maxResolution?: string;
  maxRefreshHz?: number;
  colorDepthBits?: number;
  chromaSubsampling?: "4:4:4" | "4:2:2" | "4:2:0";
  /**
   * HDCP version, e.g. '1.4', '2.2', '2.3', or 'none'.
   */
  hdcp?: string;
  /**
   * Supported HDR formats, e.g. 'hdr10', 'hdr10+', 'dolby-vision', 'hlg'.
   */
  hdr?: string[];
  /**
   * Port performs scaling/format conversion.
   */
  scaling?: boolean;
  edidManagement?: boolean;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type SignalAudio = {
  [k: string]: unknown;
} & {
  domain: "audio";
  transport?:
    | "analog"
    | "lpcm"
    | "aes3"
    | "spdif"
    | "adat"
    | "madi"
    | "arc"
    | "earc"
    | "dante"
    | "aes67"
    | "avb"
    | "milan"
    | "cobranet"
    | "livewire"
    | "usb-uac"
    | "bluetooth"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * Audio channels within one circuit (e.g. 2 for a stereo pair).
   */
  maxChannelsPerCircuit?: number;
  /**
   * For audio-over-IP, the number of network audio channels (e.g. Dante 64x64 -> 64).
   */
  networkChannels?: number;
  /**
   * Nominal level in dBu (e.g. +4 line, -10 consumer ~ -7.78 dBu).
   */
  levelDbu?: number;
  impedanceOhms?: number;
  sampleRateHz?: number;
  bitDepth?: number;
  /**
   * 48V phantom power available (typically mic inputs).
   */
  phantomPower?: boolean;
  balanced?: boolean;
  /**
   * Adjustable gain range, e.g. '0-60'.
   */
  gainDbRange?: string;
  /**
   * Max SPL for a transducer, in dB.
   */
  maxSplDb?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type SignalControl = {
  [k: string]: unknown;
} & {
  domain: "control";
  transport?:
    | "rs-232"
    | "rs-422"
    | "rs-485"
    | "ir"
    | "cec"
    | "gpio"
    | "contact-closure"
    | "relay"
    | "usb-hid"
    | "usb-cdc"
    | "cresnet"
    | "knx"
    | "dali"
    | "dmx512"
    | "artnet"
    | "sacn"
    | "onvif"
    | "sip"
    | "bacnet"
    | "modbus"
    | "mqtt"
    | "http"
    | "rest"
    | "telnet"
    | "ssh"
    | "ip-control"
    | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * e.g. '9600-115200'.
   */
  baudRange?: string;
  /**
   * IR carrier frequency, e.g. 38.
   */
  irCarrierKhz?: number;
  /**
   * e.g. 'controller', 'controlled'.
   */
  roles?: string[];
  /**
   * Bus protocol where multiple devices share the line (RS-485, DMX, KNX, DALI).
   */
  busAddressable?: boolean;
  maxBusDevices?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * General IP connectivity / infrastructure flow (LAN, control network, management). Service-specific media flows that happen to ride Ethernet (Dante, AES67, SDVoE, NDI...) are modeled under their own domain (audio/video) with the matching transport.
 */
export type SignalNetwork = {
  [k: string]: unknown;
} & {
  domain: "network";
  transport?: "ethernet" | "ip" | "control-network" | "av-network" | "management" | "vlan-trunk" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  vlanCapable?: boolean;
  managed?: boolean;
  redundancy?: "none" | "lag" | "smpte-2022-7" | "parallel" | "stp" | "other";
  /**
   * Additional transported AV/IT protocols not broken out as separate flows, e.g. 'dante', 'ndi', 'sdvoe'.
   */
  protocols?: string[];
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * Non-AV data payload (e.g. USB data, mass storage, generic file transfer).
 */
export type SignalData = {
  [k: string]: unknown;
} & {
  domain: "data";
  transport?: "usb-data" | "usb-mass-storage" | "thunderbolt" | "file-transfer" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  rateGbps?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
/**
 * Power delivery as a port's function (e.g. a DC output, 12V trigger, PDU outlet, speaker drive). Note: PoE belongs on link.poe and USB-PD on link.powerDeliveryWatts.
 */
export type SignalPower = {
  [k: string]: unknown;
} & {
  domain: "power";
  transport?: "ac" | "dc" | "usb-pd" | "phantom" | "trigger" | "wireless-power" | "other";
  transportOther?: string;
  /**
   * Direction of this specific flow; overrides the port direction when present.
   */
  direction?: "input" | "output" | "bidirectional";
  /**
   * Number of independent, separately-routable circuits of this flow carried by the port (default 1). A 3-pole RS-232 connector has channels=1; an 8-pole GPIO block has channels=8.
   */
  channels?: number;
  /**
   * source = supplies power out of this port; sink = draws power in.
   */
  role?: "source" | "sink";
  /**
   * Volts.
   */
  nominalVoltage?: number;
  maxWatts?: number;
  maxAmps?: number;
  notes?: string;
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};
export type CableEnd = {
  [k: string]: unknown;
} & {
  id?: string;
  /**
   * e.g. 'Display end', 'To RX', 'A', 'B'.
   */
  label?: string;
  /**
   * Controlled connector (physical jack) vocabulary. Use 'other' with connectorOther when not listed. The connector describes the jack only; the transmission standard belongs in port.link and the carried flows in port.signals.
   */
  connector:
    | "hdmi-type-a"
    | "hdmi-type-b"
    | "hdmi-type-c"
    | "hdmi-type-d"
    | "displayport"
    | "mini-displayport"
    | "dvi-d"
    | "dvi-i"
    | "dvi-a"
    | "hd15-vga"
    | "usb-a"
    | "usb-b"
    | "usb-b-mini"
    | "usb-b-micro"
    | "usb-c"
    | "rj45"
    | "rj45-shielded"
    | "ethercon"
    | "sfp"
    | "sfp+"
    | "sfp28"
    | "qsfp"
    | "qsfp+"
    | "qsfp28"
    | "fiber-lc"
    | "fiber-lc-duplex"
    | "fiber-sc"
    | "fiber-st"
    | "fiber-mpo"
    | "fiber-mtp"
    | "opticalcon"
    | "bnc"
    | "bnc-din-1.0-2.3"
    | "rca"
    | "f-type"
    | "toslink"
    | "mini-toslink"
    | "xlr-3-m"
    | "xlr-3-f"
    | "xlr-5-m"
    | "xlr-5-f"
    | "mini-xlr-3"
    | "mini-xlr-4"
    | "xlr-combo"
    | "euroblock-3.5mm"
    | "euroblock-5.08mm"
    | "phoenix"
    | "terminal-block"
    | "captive-screw"
    | "trs-3.5mm"
    | "trrs-3.5mm"
    | "ts-6.35mm"
    | "trs-6.35mm"
    | "speakon-nl2"
    | "speakon-nl4"
    | "speakon-nl8"
    | "binding-post"
    | "banana"
    | "db9"
    | "db15"
    | "db25"
    | "rj11"
    | "rj12"
    | "sma"
    | "rp-sma"
    | "tnc"
    | "n-type"
    | "iec-c8"
    | "iec-c14"
    | "iec-c16"
    | "iec-c20"
    | "powercon"
    | "powercon-true1"
    | "nema-5-15"
    | "barrel-dc"
    | "phoenix-power"
    | "other";
  connectorOther?: string;
  gender?: "male" | "female";
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
} & {
  id?: string;
  /**
   * e.g. 'Display end', 'To RX', 'A', 'B'.
   */
  label?: string;
  /**
   * Controlled connector (physical jack) vocabulary. Use 'other' with connectorOther when not listed. The connector describes the jack only; the transmission standard belongs in port.link and the carried flows in port.signals.
   */
  connector:
    | "hdmi-type-a"
    | "hdmi-type-b"
    | "hdmi-type-c"
    | "hdmi-type-d"
    | "displayport"
    | "mini-displayport"
    | "dvi-d"
    | "dvi-i"
    | "dvi-a"
    | "hd15-vga"
    | "usb-a"
    | "usb-b"
    | "usb-b-mini"
    | "usb-b-micro"
    | "usb-c"
    | "rj45"
    | "rj45-shielded"
    | "ethercon"
    | "sfp"
    | "sfp+"
    | "sfp28"
    | "qsfp"
    | "qsfp+"
    | "qsfp28"
    | "fiber-lc"
    | "fiber-lc-duplex"
    | "fiber-sc"
    | "fiber-st"
    | "fiber-mpo"
    | "fiber-mtp"
    | "opticalcon"
    | "bnc"
    | "bnc-din-1.0-2.3"
    | "rca"
    | "f-type"
    | "toslink"
    | "mini-toslink"
    | "xlr-3-m"
    | "xlr-3-f"
    | "xlr-5-m"
    | "xlr-5-f"
    | "mini-xlr-3"
    | "mini-xlr-4"
    | "xlr-combo"
    | "euroblock-3.5mm"
    | "euroblock-5.08mm"
    | "phoenix"
    | "terminal-block"
    | "captive-screw"
    | "trs-3.5mm"
    | "trrs-3.5mm"
    | "ts-6.35mm"
    | "trs-6.35mm"
    | "speakon-nl2"
    | "speakon-nl4"
    | "speakon-nl8"
    | "binding-post"
    | "banana"
    | "db9"
    | "db15"
    | "db25"
    | "rj11"
    | "rj12"
    | "sma"
    | "rp-sma"
    | "tnc"
    | "n-type"
    | "iec-c8"
    | "iec-c14"
    | "iec-c16"
    | "iec-c20"
    | "powercon"
    | "powercon-true1"
    | "nema-5-15"
    | "barrel-dc"
    | "phoenix-power"
    | "other";
  connectorOther?: string;
  gender?: "male" | "female";
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
};

/**
 * A cable (often factory-terminated) described by its typed ends and length. Usable as a standalone document or embedded as a bundle component. Reuses the device schema's connector and signal vocabularies.
 */
export interface OpenDeviceIOCable {
  $schema?: string;
  odioVersion: string;
  kind: "cable";
  id: string;
  cable: Cable;
  provenance?: Provenance;
  /**
   * This interface was referenced by `OpenDeviceIOCable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * The cable body. May be embedded in a bundle component or wrapped as a standalone cable document.
 */
export interface Cable {
  manufacturer?: string;
  /**
   * Cable part number / model.
   */
  model?: string;
  sku?: string;
  label?: string;
  /**
   * True if terminated at the factory (vs field-terminated).
   */
  factoryTerminated?: boolean;
  lengthMeters?: number;
  /**
   * Length as printed, e.g. '6 ft (1.8 m)'.
   */
  lengthLabel?: string;
  shielded?: boolean;
  plenum?: boolean;
  /**
   * Signal(s) the cable conveys end to end (reuses the device signal model).
   */
  carries?: Signal[];
  /**
   * The cable's terminations. Usually 2; more for breakout/snake cables.
   *
   * @minItems 1
   */
  ends: [CableEnd, ...CableEnd[]];
  notes?: string;
  /**
   * This interface was referenced by `Cable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Where this data came from and how trustworthy it is.
 */
export interface Provenance {
  /**
   * Tool that produced the file, e.g. 'genie/0.1.0', or 'manual'.
   */
  generator?: string;
  method?: "llm-extraction" | "manual" | "manufacturer";
  sourceDocuments?: {
    title?: string;
    url?: string;
    sha256?: string;
    retrieved?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  }[];
  validation?: {
    status?: "draft" | "reviewed" | "manufacturer-verified";
    by?: string;
    date?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  confidence?: {
    overall?: number;
    /**
     * JSON paths the generator was unsure about, for human review.
     */
    lowConfidenceFields?: string[];
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * This interface was referenced by `Provenance`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
