// Generates bundled, self-contained copies of the canonical JSON Schemas
// (src/schema.ts for the device schema, src/bundle-schema.ts for the bundle and
// cable schemas) and TypeScript interfaces (src/types.ts for the device,
// src/bundle-types.ts for Bundle/Cable) from the canonical schemas under
// ../../schema/v0.1/.
//
// The generated files are committed as source so consumers get types and
// bundled schemas without running codegen, and the published package does not
// depend on the filesystem location of the canonical schemas.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const srcDir = path.join(pkgRoot, "src");
const schemaDir = path.resolve(pkgRoot, "..", "..", "schema", "v0.1");

const deviceSchemaPath = path.join(schemaDir, "device.schema.json");
const bundleSchemaPath = path.join(schemaDir, "bundle.schema.json");
const cableSchemaPath = path.join(schemaDir, "cable.schema.json");

const deviceRaw = await readFile(deviceSchemaPath, "utf8");
const bundleRaw = await readFile(bundleSchemaPath, "utf8");
const cableRaw = await readFile(cableSchemaPath, "utf8");

const deviceSchema = JSON.parse(deviceRaw);
const bundleSchema = JSON.parse(bundleRaw);
const cableSchema = JSON.parse(cableRaw);

// Canonical $id URLs -> in-memory schema, so json-schema-to-typescript can
// resolve the cross-document https:// $refs without network access.
const byUrl = {
  "https://opendeviceio.org/schema/v0.1/device.schema.json": deviceSchema,
  "https://opendeviceio.org/schema/v0.1/bundle.schema.json": bundleSchema,
  "https://opendeviceio.org/schema/v0.1/cable.schema.json": cableSchema
};

const urlResolver = {
  order: 1,
  canRead: /^https:\/\/opendeviceio\.org\/schema\//,
  read(file) {
    const schema = byUrl[file.url];
    if (!schema) throw new Error(`gen-types: no in-memory schema for ${file.url}`);
    return JSON.stringify(schema);
  }
};

// --- 1. Bundle the schemas as TS modules (works in ESM and CJS, no JSON
//        import assertions / module-resolution caveats). ---
function schemaModule(varName, sourceFile, schema, extra = "") {
  return `// AUTO-GENERATED by scripts/gen-types.mjs. DO NOT EDIT BY HAND.
// Self-contained copy of the canonical OpenDeviceIO schema
// (schema/v0.1/${sourceFile}).${extra} Regenerate with \`npm run gen-types\`.

/* eslint-disable */
const ${varName} = ${JSON.stringify(schema, null, 2)} as const;

export default ${varName};
`;
}

await writeFile(
  path.join(srcDir, "schema.ts"),
  schemaModule("deviceSchema", "device.schema.json", deviceSchema),
  "utf8"
);

// Bundle + cable schemas live together (cross-referencing each other and the
// device schema); ship both from one module.
const bundleSchemaModule = `// AUTO-GENERATED by scripts/gen-types.mjs. DO NOT EDIT BY HAND.
// Self-contained copies of the canonical OpenDeviceIO bundle and cable schemas
// (schema/v0.1/bundle.schema.json, schema/v0.1/cable.schema.json).
// Regenerate with \`npm run gen-types\`.

/* eslint-disable */
export const bundleSchema = ${JSON.stringify(bundleSchema, null, 2)} as const;

export const cableSchema = ${JSON.stringify(cableSchema, null, 2)} as const;
`;
await writeFile(path.join(srcDir, "bundle-schema.ts"), bundleSchemaModule, "utf8");

// --- 2. Generate TypeScript interfaces from the schemas. ---
const deviceTypes = await compile(deviceSchema, "Device", {
  additionalProperties: false,
  bannerComment:
    "// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/device.schema.json.\n// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`.",
  style: {
    singleQuote: false,
    semi: true
  }
});
await writeFile(path.join(srcDir, "types.ts"), deviceTypes, "utf8");

const j2tOpts = {
  additionalProperties: false,
  $refOptions: { resolve: { odio: urlResolver } },
  style: { singleQuote: false, semi: true }
};

const bundleTypes = await compile(bundleSchema, "Bundle", {
  ...j2tOpts,
  bannerComment:
    "// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/bundle.schema.json.\n// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`."
});
const cableTypes = await compile(cableSchema, "Cable", {
  ...j2tOpts,
  bannerComment:
    "// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/cable.schema.json.\n// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`."
});

await writeFile(path.join(srcDir, "bundle-types.ts"), bundleTypes, "utf8");
await writeFile(path.join(srcDir, "cable-types.ts"), cableTypes, "utf8");

console.log(
  "gen-types: wrote src/schema.ts, src/bundle-schema.ts, src/types.ts, src/bundle-types.ts, src/cable-types.ts"
);
