// Generates src/schema.ts (a bundled, self-contained copy of the canonical
// JSON Schema) and src/types.ts (TypeScript interfaces) from the canonical
// schema at ../../schema/v0.1/device.schema.json.
//
// The generated files are committed as source so consumers get types and a
// bundled schema without running codegen, and the published package does not
// depend on the filesystem location of the canonical schema.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { compile } from "json-schema-to-typescript";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, "..");
const srcDir = path.join(pkgRoot, "src");
const canonicalSchemaPath = path.resolve(
  pkgRoot,
  "..",
  "..",
  "schema",
  "v0.1",
  "device.schema.json"
);

const raw = await readFile(canonicalSchemaPath, "utf8");
const schema = JSON.parse(raw);

// --- 1. Bundle the schema as a TS module (works in ESM and CJS, no JSON
//        import assertions / module-resolution caveats). ---
const schemaModule = `// AUTO-GENERATED by scripts/gen-types.mjs. DO NOT EDIT BY HAND.
// Self-contained copy of the canonical OpenDeviceIO device schema
// (schema/v0.1/device.schema.json). Regenerate with \`npm run gen-types\`.

/* eslint-disable */
const deviceSchema = ${JSON.stringify(schema, null, 2)} as const;

export default deviceSchema;
`;
await writeFile(path.join(srcDir, "schema.ts"), schemaModule, "utf8");

// --- 2. Generate TypeScript interfaces from the schema. ---
const types = await compile(schema, "Device", {
  additionalProperties: false,
  bannerComment:
    "// AUTO-GENERATED by scripts/gen-types.mjs from schema/v0.1/device.schema.json.\n// DO NOT EDIT BY HAND. Regenerate with `npm run gen-types`.",
  style: {
    singleQuote: false,
    semi: true
  }
});
await writeFile(path.join(srcDir, "types.ts"), types, "utf8");

console.log("gen-types: wrote src/schema.ts and src/types.ts");
